test(e2e): add e2e framework (`bats`), add e2e CI, and update source code of test files
dfinity/dfx-extensions pull request #17
Opened 2023-05-10 15:03 UTC by smallstepman

see checks for this PR: https://github.com/dfinity/dfx-extensions/pull/17/checks

2023-05-10 17:16 UTC, ericswanson-dfinity requested changes

2023-05-10 17:16 UTC, ericswanson-dfinity commented on extensions/sns/e2e/tests-dfx/sns.bash
> +    run dfx extension run sns config validate
```suggestion
    run Forrest run sns config validate
```

2023-05-10 17:16 UTC, ericswanson-dfinity commented on e2e/e2e_utils.sh
> +set -e
Does this file need `e2e` in both its directory and filename?

2023-05-10 17:18 UTC, smallstepman commented on .github/workflows/e2e.yml
> +        test_file_path: [ extensions/nns/e2e/tests-dfx/nns.bash, extensions/sns/e2e/tests-dfx/sns.bash ]
Right, I'll rename the directories. regarding the matrix, I opted for simplicity, [e2e-matrix.py](https://github.com/dfinity/sdk/blob/master/scripts/workflows/e2e-matrix.py) can always be added later once the amount of files grows past 3 or 5. I want these e2e test to be simple to comprehend for future extension owners

2023-06-29 17:17 UTC, ericswanson-dfinity commented on extensions/sns/src/commands/config/create.rs
> +        anyhow::bail!("Cannot find dfx configuration file in the current working directory. Did you forget to create one?");
There's an opportunity to DRY here: see this and the following three changes with identical messaging

2023-06-29 17:23 UTC, ericswanson-dfinity requested changes
please DRY

2023-06-30 16:14 UTC, ericswanson-dfinity commented on extensions/sns/src/errors.rs
> +pub static DFXJSON_NOT_FOUND: &str = "Cannot find dfx configuration file in the current working directory. Did you forget to create one?";
Super curious why this isn't in https://github.com/dfinity/dfx-extensions/tree/main/extensions-utils/src

2023-06-30 16:18 UTC, ericswanson-dfinity approved these changes

2023-06-30 16:18 UTC, merged